### PR TITLE
Sorting out issue with calling predict on matrix

### LINKED ISSUE #218: Calling predict on matrix throws error
Not sure if this is by design, but calling predict on a matrix throws an error. 

Using the example from the README:

```julia
# Example from README:
using MLJ
import RDatasets
iris = RDatasets.dataset("datasets", "iris");
y, X = unpack(iris, ==(:Species), colname -> true, rng=123);
NeuralNetworkClassifier = @load NeuralNetworkClassifier pkg=MLJFlux
clf = NeuralNetworkClassifier()
mach = machine(clf, X, y)
fit!(mach)
```

The following throws an error related to formatting:

```julia
julia> Xmat = permutedims(MLJ.matrix(X))
4×150 Matrix{Float64}:
 6.7  5.7  7.2  4.4  5.6  6.5  4.4  6.1  …  6.1  6.7  5.0  7.6  6.3  5.1  5.0
 3.3  2.8  3.0  2.9  2.5  3.0  3.0  2.9     2.8  2.5  3.5  3.0  2.5  3.8  3.6
 5.7  4.1  5.8  1.4  3.9  5.2  1.3  4.7     4.0  5.8  1.3  6.6  5.0  1.6  1.4
 2.1  1.3  1.6  0.2  1.1  2.0  0.2  1.4     1.3  1.8  0.3  2.1  1.9  0.2  0.2

julia> predict(mach, Xmat)
ERROR: 

────────────────────────────────── MethodError ─────────────────────────────────
╭──── Error Stack ─────────────────────────────────────────────────────────────╮
│                                                                              │
│                                                                              │
│  ╭──────────────────────────────────────────────────────────────────╮        │
│  │                                                                  │        │
│  │  (1) top-level scope                                             │        │
│  │      ~/.julia/packages/CUDA/BbliS/src/initialization.j           │        │
│  │      l:52                                                        │        │
│  │        │ ╭────────────────────────────────────────────────────   │        │
│  │  ──────╮                                                         │        │
│  │        ╰─│    50     quote                                       │        │
│  │             │                                                    │        │
│  │          │    51         try                                     │        │
│  │             │                                                    │        │
│  │          │  ❯ 52             $(ex)                               │        │
│  │             │                                                    │        │
│  │          │    53         finally                                 │        │
│  │             │                                                    │        │
│  │          │    54             $task_local_state()...              │        │
│  │             │                                                    │        │
│  │          ╰─────────────────────── error line ─────────────────   │        │
│  │  ──────╯                                                         │        │
│  │                                                                  │        │
│  ╰──────────────────────────────────────────────────── TOP LEVEL ───╯        │
│                                                                              │
│     (2) top-level scope                                                      │
│         REPL[43]:1                                                           │
│                                                                              │
│     ────────────────────────────────────────────────────────────────────     │
│                         Skipped 1 frames in MLJBase                          │
│     ────────────────────────────────────────────────────────────────────     │
│                                                                              │
│  ╭──────────────────────────────────────────────────────────────────╮        │
│  │                                                                  │        │
│  │  (5) reformat(X::Matrix)                                         │        │
│  │      ~/.julia/packages/MLJFlux/6XVNm/src/core.jl:145             │        │
│  │        │ ╭────────────────────────────────────────────────────   │        │
│  │  ──────╮                                                         │        │
│  │        ╰─│    143 nrows(y::AbstractVector) = length(y)           │        │
│  │             │                                                    │        │
│  │          │    144                                                │        │
│  │             │                                                    │        │
│  │          │  ❯ 145 reformat(X) = reformat(X, scitype(X))          │        │
│  │             │                                                    │        │
│  │          │    146                                                │        │
│  │             │                                                    │        │
│  │          │    147 # ---------------------------------            │        │
│  │             │                                                    │        │
│  │          ╰─────────────────────── error line ─────────────────   │        │
│  │  ──────╯                                                         │        │
│  │                                                                  │        │
│  ╰─────────────────────────────────────────────────── ERROR LINE ───╯        │
│                                                                              │
╰──── Error Stack ─────────────────────────────────────────────────────────────╯
╭───────────────────────────────── MethodError ────────────────────────────────╮
│                                                                              │
│  No method matching `reformat` with arguments types:                         │
│  ::Matrix, ::DataType                                                        │
│                                                                              │
│  Alternative candidates:                                                     │
│    reformat(::Any)                                                           │
│    reformat(::Any, ::Type{<:Table})                                          │
│    reformat(::Any, ::Type{<:GrayImage})                                      │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
```

Will create a PR for this issue in a moment that simply adds the following to `core.jl`:

```julia
reformat(X, ::Type{<:AbstractMatrix}) = X
```

Looks redundant but works 😄

### PR DESCRIPTION
**Pull request by pat-alt**
Closes #218

### CODE REVIEW

File: src/core.jl [hunk 1]
```diff
@@ -144,6 +144,10 @@ nrows(y::AbstractVector) = length(y)
 
 reformat(X) = reformat(X, scitype(X))
 
+# ---------------------------------
+# Reformatting matrices
+reformat(X, ::Type{<:AbstractMatrix}) = permutedims(X)
```
Comment (ablaom) [inline src/core.jl:149]: Yes, when MLJ users provide inputs in the form of a matrix, the observations are rows, which is the opposite of what the internal Flux operations are expecting. 

However, I wouldn't we be better off with and adjoint here, instead of `permute dims`? Then, if a user provides an adjoint, the adjoints cancel and there is no performance cost at all. No?

**Review by ablaom — COMMENTED** [review]
@pat-alt Thanks for looking at this. 

Yes, I think your proposal ought to work: matrices can be provided not only to predict, but also to fit, which we should have for consistency.

What's left to do is:

- [x] Add tests
- [x] Update the scitype declarations
- [x] Update the docstrings

For example, [this code](https://github.com/FluxML/MLJFlux.jl/blob/452c09d7dc13914f4057c661448bc310c9362d3d/src/classifier.jl#L30) should be changed to 

```julia
MLJModelInterface.metadata_model(NeuralNetworkClassifier,
                                 input=Union{AbstractMatrix{Continuous}, Table(Continuous)},
                                 target=AbstractVector{<:Finite},
                                 path="MLJFlux.NeuralNetworkClassifier")
```
Similar changes can be made at regressor.jl

File: src/core.jl (hunk 1 above)
Comment (pat-alt) [reply src/core.jl]: Yes, good point! Have changed that

**Comment by pat-alt** [comment]
I've updated the scitype declarations for regression ([here](https://github.com/FluxML/MLJFlux.jl/blob/3c369154d85faadd533219bcef79ba4078d7bc54/src/regressor.jl#L23) and [here](https://github.com/FluxML/MLJFlux.jl/blob/3c369154d85faadd533219bcef79ba4078d7bc54/src/regressor.jl#L55)) and for classification ([here](https://github.com/FluxML/MLJFlux.jl/blob/3c369154d85faadd533219bcef79ba4078d7bc54/src/classifier.jl#L30)). For testing, I thought I'd just rerun basic tests with a matrix input (see [here](https://github.com/FluxML/MLJFlux.jl/blob/3c369154d85faadd533219bcef79ba4078d7bc54/test/classifier.jl#L39)). Unfortunately, I can't immediately make sense of the error I'm getting.

**Comment by ablaom** [comment]
Thanks for persisting with this.

This error usually means we're trying to grab the `schema` of an object that doesn't have one. I believe the culprit is [here](https://github.com/pat-alt/MLJFlux.jl/blob/3c369154d85faadd533219bcef79ba4078d7bc54/src/classifier.jl#L6). We could add a second method dispatching on matrices to address. There are similar issues for `shape` in regressor.jl.

**Comment by pat-alt** [comment]
Thanks! I believe that's fixed now, though I did still get some warnings like this one:

```julia
Warning: The number and/or types of data arguments do not match what the specified model
│ supports. Suppress this type check by specifying `scitype_check_level=0`.
│ 
│ Run `@doc MLJFlux.NeuralNetworkRegressor` to learn more about your model's requirements.
│ 
│ Commonly, but non exclusively, supervised models are constructed using the syntax
│ `machine(model, X, y)` or `machine(model, X, y, w)` while most other models are
│ constructed with `machine(model, X)`.  Here `X` are features, `y` a target, and `w`
│ sample or class weights.
│ 
│ In general, data in `machine(model, data...)` is expected to satisfy
│ 
│     scitype(data) <: MLJ.fit_data_scitype(model)
│ 
│ In the present case:
│ 
│ scitype(data) = Tuple{Table{AbstractVector{Continuous}}, AbstractVector{Continuous}}
│ 
│ fit_data_scitype(model) = Tuple{Union{Table{<:AbstractVector{<:Continuous}}, AbstractMatrix{Continuous}}, AbstractVector{<:Finite}}
```

**Comment by ablaom** [comment]
> Thanks! I believe that's fixed now, though I did still get some warnings like this one:

According to the warning you are providing the regressor with a `Continuous` target, rather than a `Finite` one (categorical vector).

**Comment by ablaom** [comment]
Sorry, rather the scitype declaration for the regressor is wrong. You need `Continuous` in the `target_scitype` where you appear to have `Finite`.

**Comment by pat-alt** [comment]
> Sorry, rather the scitype declaration for the regressor is wrong. You need `Continuous` in the `target_scitype` where you appear to have `Finite`.

You're right, thanks. Fixed that now, but I still get some broken tests (e.g. [here](https://github.com/FluxML/MLJFlux.jl/actions/runs/4674766928/jobs/8279249059?pr=219#step:6:405). Is this expected?

**Comment by ablaom** [comment]
> Fixed that now, but I still get some broken tests (e.g. [here](https://github.com/FluxML/MLJFlux.jl/actions/runs/4674766928/jobs/8279249059?pr=219#step:6:405). Is this expected?

Yes. Some of the broken tests are because you are looking at CPU tests, where some tests are excluded and get marked as broken. 

The remaining broken tests are explained here https://github.com/FluxML/MLJFlux.jl/issues/87 .

So no further action on your part needed here. I will finish my review shortly, thanks.

**Review by ablaom — APPROVED** [review]
I'm happy this as is. 

However, perhaps you would consider one additional enhancement, for consistency:
The MulitargetNeuralNetworkRegressor accepts the *target* as a table, but not as a matrix. It seems this would not be difficult to fix (but I haven't checked):

- In [`fitresult(model::MultitargetNeuralNetworkRegressor, chain, y)` method](https://github.com/FluxML/MLJFlux.jl/blob/d01f5366f6cca73d8bd650ac1ab7e4c14735fd77/src/regressor.jl#L53)  return `nothing` instead of `Table.schema(y).names` if `y` is a matrix. 
- In [`shape`](https://github.com/FluxML/MLJFlux.jl/blob/d01f5366f6cca73d8bd650ac1ab7e4c14735fd77/src/regressor.jl#L42) make the change for treating `y` you already have made for `X`.
- In [`predict`](https://github.com/FluxML/MLJFlux.jl/blob/d01f5366f6cca73d8bd650ac1ab7e4c14735fd77/src/regressor.jl#L57) return a matrix if `target_column_names` is `nothing`.  

If you'd rather proceed as we are, then I'll just open an new issue and reference this comment.

**Comment by pat-alt** [comment]
Thanks, good idea! I've made the necessary adjustments and updated tests accordingly. Had to make one additional small modification to the `collate` function. I've also updated the docstring.

File: src/core.jl [hunk 2]
```diff
@@ -224,6 +224,7 @@ by `model.batch_size`.)
 
 """
 function collate(model, X, y)
+    y = y isa Matrix ? Tables.table(y) : y
```
Comment (ablaom) [inline src/core.jl:227]: I'm trying to understand why this fix was needed. The `nrows` function is supposed to work for matrices as well as tables:

```julia
using MLJBase
julia> y = rand(2, 6)
julia> nrows(y)
2

julia> nrows(y')
6
```
And line 230 below should already take care of the conversion of `y` to a matrix, no?

File: src/regressor.jl [hunk 3]
```diff
@@ -12,23 +18,30 @@ build(model::NeuralNetworkRegressor, rng, shape) =
...
+    shape(model::MultitargetNeuralNetworkRegressor, X, y)
+
+A private method that returns the shape of the input and output of the model for given data `X` and `y`.
+"""
 function shape(model::MultitargetNeuralNetworkRegressor, X, y)
+    X = X isa Matrix ? Tables.table(X) : X
+    y = y isa Matrix ? Tables.table(y) : y
     n_input = Tables.schema(X).names |> length
     n_output = Tables.schema(y).names |> length
     return (n_input, n_output)
```
Comment (ablaom) [inline src/regressor.jl:47]: Sorry for not catching this earlier, but wrapping a matrix as a table seems a convoluted  way to get num  columns. 

What about something like this?
```suggestion
ncols(X::AbstractMatrix) = size(X, 2)
ncols(X) = Tables.columns(X)) |> Tables.columnnames |> length
shape(model::MultitargetNeuralNetworkRegressor, X, y) = (ncols(X), ncols(y))
```

(Note, I've also dumped `Tables.schema` in favour of different Tables methods, which should be more reliable: `schema` should only be applied to `Tables.rows(X)` or `Tables.columns(X)` and can give `nothing` if not implemented for a particular table. Unfortunately, one cannot avoid `Tables.rows(X)` or `Tables.columns(X)` to get reliably get the number of columns through Tables.jl API, as far as I can understand.)

Comment (pat-alt) [reply src/regressor.jl]: That makes more sense, yes!

File: src/core.jl (hunk 2 above)
Comment (pat-alt) [reply src/core.jl]: This was giving me an error previously, because the `nrows` method defined in the same file expects a table (or else it throws an `ArgumentError`. I've adjusted that and tests are passing.

File: src/core.jl [hunk 4]
```diff
@@ -141,6 +141,7 @@ function nrows(X)
     return length(cols[1])
 end
 nrows(y::AbstractVector) = length(y)
+nrows(X::AbstractMatrix) = size(X, 1)
```
Comment (ablaom) [inline src/core.jl:145]: Oh, I see. We're not using `nrows` from MLJBase.jl - I forgot. Thanks for humouring me with the explanation!

**Review by ablaom — APPROVED** [review]
Looks good to go.
